# Pandas - Missing Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
dic = {
    'A': [1, 2, np.nan],
    'B': [5, np.nan, np.nan],
    'C': [1, 2, 3]
}

In [3]:
df = pd.DataFrame(dic)
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [4]:
df.dropna() # drops ANY rows containing missing values, `inplace` is present

     A    B  C
0  1.0  5.0  1

In [5]:
df.dropna(axis = 1) # drops ANY columns containing missing values

   C
0  1
1  2
2  3

In [6]:
df.dropna(thresh = 2) # requires that rows with at least 2 non-NA values not be dropped

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [7]:
df.fillna(value = 'TBD') # replaces NA values with 'TBD', `inplace` is also present

     A    B  C
0  1.0  5.0  1
1  2.0  TBD  2
2  TBD  TBD  3

In [8]:
df['A'].fillna(value = df['A'].mean()) # replaces NA values in column A with the mean

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64