In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    'one': [12, 15, 54, 69, 96, 100],
    'two': [1, 1, 2, 2, 3, 3],
    'three': [6, 24, 15, 60, 45, 36]
})
df

   one  two  three
0   12    1      6
1   15    1     24
2   54    2     15
3   69    2     60
4   96    3     45
5  100    3     36

In [ ]:
df['one'].unique() # returns unique values in column 'one'

array([ 12,  15,  54,  69,  96, 100], dtype=int64)

In [ ]:
df['one'].nunique() # returns the number of unique values instead

6

In [ ]:
df['two'].value_counts() # returns the frequency of values

two
1    2
2    2
3    2
Name: count, dtype: int64

In [6]:
df['one'].sum() # a basic function

np.int64(346)

In [7]:
df['one'].apply(lambda x : x * 2) # applies a function

0     24
1     30
2    108
3    138
4    192
5    200
Name: one, dtype: int64

In [8]:
# You can also apply a built-in function

In [9]:
df.drop('two', axis = 1) # drops that column, 'inplace' is present

   one  three
0   12      6
1   15     24
2   54     15
3   69     60
4   96     45
5  100     36

In [10]:
df.columns # a list of column names

Index(['one', 'two', 'three'], dtype='str')

In [11]:
df.index # a list of indexes

RangeIndex(start=0, stop=6, step=1)

In [12]:
df.sort_values('three') # sorts the column
# df.sort_values(by = 'three') same thing

   one  two  three
0   12    1      6
2   54    2     15
1   15    1     24
5  100    3     36
4   96    3     45
3   69    2     60

In [13]:
df.isnull() # returns boolean values indicating whether a value is null

     one    two  three
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [14]:
tmp = pd.DataFrame({
    'A': 'foo foo foo bar bar bar'.split(' '),
    'B': 'one one two two one one'.split(' '),
    'C': 'x y x y x y'.split(' '),
    'D': [1, 3, 2, 5, 4, 1]
})
tmp

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [15]:
tmp.pivot_table(values = 'D', index = ['A', 'B'], columns = ['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN